package de.george.lrentnode.classes;

import de.george.g3utils.io.G3FileReader;
import de.george.g3utils.io.G3FileWriter;
import de.george.g3utils.structure.bCMatrix;
import de.george.g3utils.structure.bCVector;
import de.george.lrentnode.properties.eCEntityProxy;

public class gCCameraAI_PS extends G3Class {
	private float unk1E8;
	private float unk1EC;
	private float unk1F0;
	private float unk1F4;
	private float unk1F8;
	private boolean unk1FC;
	private boolean unk1FD;
	private boolean unk1FE;
	private boolean unk1FF;
	private boolean unk200;
	private boolean unk201;
	private boolean unk202;
	private boolean unk203;
	private boolean unk204;
	private boolean unk205;
	private float unk208;
	private float unk20C;
	private float unk210;
	private float unk214;
	private float unk218;
	private float unk21C;
	private float unk220;
	private float unk224;
	private float unk228;
	private bCMatrix unk22C;
	private bCMatrix unk26C;
	private bCMatrix unk2AC;
	private bCVector unk2EC;
	private bCVector unk2F8;
	private bCVector unk304;
	private bCVector unk310;
	private bCVector unk31C;
	private bCVector unk328;
	private bCVector unk334;
	private bCVector unk340;
	private bCVector unk34C;
	private float unk358;
	private float unk35C;
	private float unk360;
	private float unk364;
	private float unk368;
	private float unk36C;
	private float unk370;
	private float unk374;
	private bCVector unk378;
	private bCVector unk384;
	private boolean unk390;
	private float unk394;
	private float unk398;
	private float unk39C;
	private float unk3A0;
	private float unk3A4;
	private float unk3A8;
	private float unk3AC;
	private float unk3B0;
	private float unk3B4;
	private long unk3B8;
	private long unk3BC;
	private boolean unk3C0;
	private boolean unk3C1;
	private boolean unk3C2;
	private boolean unk3C3;
	private boolean unk3C4;
	private boolean unk3C6;
	private boolean unk3C7;
	private boolean unk3C9;
	private float unk3CC;
	private float unk3D0;
	private eCEntityProxy unk3EC;

	public gCCameraAI_PS(String className, G3FileReader reader) {
		super(className, reader);
	}

	@Override
	protected void readPostClassVersion(G3FileReader reader) {
		if (classVersion <= 0x32)
			return;

		unk1E8 = reader.readFloat();
		unk1EC = reader.readFloat();
		unk1F0 = reader.readFloat();
		unk1F4 = reader.readFloat();
		unk1F8 = reader.readFloat();
		unk1FC = reader.readBool();
		unk1FD = reader.readBool();
		unk1FE = reader.readBool();
		unk1FF = reader.readBool();
		unk200 = reader.readBool();
		unk201 = reader.readBool();
		unk202 = reader.readBool();
		unk203 = reader.readBool();
		unk204 = reader.readBool();
		unk205 = reader.readBool();
		unk208 = reader.readFloat();
		unk20C = reader.readFloat();
		unk210 = reader.readFloat();
		unk214 = reader.readFloat();
		unk218 = reader.readFloat();
		unk21C = reader.readFloat();
		unk220 = reader.readFloat();
		unk224 = reader.readFloat();
		unk228 = reader.readFloat();
		unk22C = reader.read(bCMatrix.class);
		unk26C = reader.read(bCMatrix.class);
		unk2AC = reader.read(bCMatrix.class);
		unk2EC = reader.readVector();
		unk2F8 = reader.readVector();
		unk304 = reader.readVector();
		unk310 = reader.readVector();
		unk31C = reader.readVector();
		unk328 = reader.readVector();
		unk334 = reader.readVector();
		unk340 = reader.readVector();
		unk34C = reader.readVector();
		unk358 = reader.readFloat();
		unk35C = reader.readFloat();
		unk360 = reader.readFloat();
		unk364 = reader.readFloat();
		unk368 = reader.readFloat();
		unk36C = reader.readFloat();
		unk370 = reader.readFloat();
		unk374 = reader.readFloat();
		unk378 = reader.readVector();
		unk384 = reader.readVector();
		unk390 = reader.readBool();
		unk394 = reader.readFloat();
		unk398 = reader.readFloat();
		unk39C = reader.readFloat();
		unk3A0 = reader.readFloat();
		unk3A4 = reader.readFloat();
		unk3A8 = reader.readFloat();
		unk3AC = reader.readFloat();
		unk3B0 = reader.readFloat();
		unk3B4 = reader.readFloat();
		unk3B8 = reader.readUnsignedInt();
		unk3BC = reader.readUnsignedInt();
		unk3C0 = reader.readBool();
		unk3C1 = reader.readBool();
		unk3C2 = reader.readBool();
		unk3C3 = reader.readBool();
		unk3C4 = reader.readBool();
		unk3C6 = reader.readBool();
		unk3C7 = reader.readBool();
		unk3C9 = reader.readBool();
		unk3CC = reader.readFloat();
		unk3D0 = reader.readFloat();
		unk3EC = reader.read(eCEntityProxy.class);
	}

	@Override
	protected void writePostClassVersion(G3FileWriter writer) {
		if (classVersion <= 0x32)
			return;

		writer.writeFloat(unk1E8);
		writer.writeFloat(unk1EC);
		writer.writeFloat(unk1F0);
		writer.writeFloat(unk1F4);
		writer.writeFloat(unk1F8);
		writer.writeBool(unk1FC);
		writer.writeBool(unk1FD);
		writer.writeBool(unk1FE);
		writer.writeBool(unk1FF);
		writer.writeBool(unk200);
		writer.writeBool(unk201);
		writer.writeBool(unk202);
		writer.writeBool(unk203);
		writer.writeBool(unk204);
		writer.writeBool(unk205);
		writer.writeFloat(unk208);
		writer.writeFloat(unk20C);
		writer.writeFloat(unk210);
		writer.writeFloat(unk214);
		writer.writeFloat(unk218);
		writer.writeFloat(unk21C);
		writer.writeFloat(unk220);
		writer.writeFloat(unk224);
		writer.writeFloat(unk228);
		writer.write(unk22C);
		writer.write(unk26C);
		writer.write(unk2AC);
		writer.writeVector(unk2EC);
		writer.writeVector(unk2F8);
		writer.writeVector(unk304);
		writer.writeVector(unk310);
		writer.writeVector(unk31C);
		writer.writeVector(unk328);
		writer.writeVector(unk334);
		writer.writeVector(unk340);
		writer.writeVector(unk34C);
		writer.writeFloat(unk358);
		writer.writeFloat(unk35C);
		writer.writeFloat(unk360);
		writer.writeFloat(unk364);
		writer.writeFloat(unk368);
		writer.writeFloat(unk36C);
		writer.writeFloat(unk370);
		writer.writeFloat(unk374);
		writer.writeVector(unk378);
		writer.writeVector(unk384);
		writer.writeBool(unk390);
		writer.writeFloat(unk394);
		writer.writeFloat(unk398);
		writer.writeFloat(unk39C);
		writer.writeFloat(unk3A0);
		writer.writeFloat(unk3A4);
		writer.writeFloat(unk3A8);
		writer.writeFloat(unk3AC);
		writer.writeFloat(unk3B0);
		writer.writeFloat(unk3B4);
		writer.writeUnsignedInt(unk3B8);
		writer.writeUnsignedInt(unk3BC);
		writer.writeBool(unk3C0);
		writer.writeBool(unk3C1);
		writer.writeBool(unk3C2);
		writer.writeBool(unk3C3);
		writer.writeBool(unk3C4);
		writer.writeBool(unk3C6);
		writer.writeBool(unk3C7);
		writer.writeBool(unk3C9);
		writer.writeFloat(unk3CC);
		writer.writeFloat(unk3D0);
		writer.write(unk3EC);
	}
}
